name:                spacetraders
version:             0.1.0.0
github:              "adyxax/spacetraders"
license:             EUPL-1.2
author:              "Julien Dessaux"
maintainer:          "julien.dessaux@adyxax.org"
copyright:           "2023 Julien Dessaux"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            My spacetraders.io game client implementation 
category:            Games

description:         Please see the README on GitHub at <https://github.com/adyxax/spacetraders#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- directory
- http-conduit
- http-types
- raw-strings-qq
- sqlite-simple
- text
- time
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  spacetraders-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spacetraders

tests:
  spacetraders-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spacetraders
